manifest:
  defaults:
    revision: v0.3
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: inorichi
      url-base: https://github.com/inorichi
    - name: hsgw
      url-base: https://github.com/hsgw
    - name: caksoylar # <-- led
      url-base: https://github.com/caksoylar

  projects:
    # ZMK 本体。公式の app/west.yml を取り込む
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml

    # PMW3610 ドライバ（外部モジュール）- automouse-layer/scroll-layers サポート版
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main

    # Sensor-rotation
    - name: zmk-feature-sensor_rotation
      remote: hsgw
      revision: main

    # LED
    - name: zmk-rgbled-widget # <-- led
      remote: caksoylar
      revision: main

  self:
    path: config
